#!/bin/bash

function usage(){

	printf "bash base64encode -s \"Hello world\"\n"
	printf "bash base64encode -f \"/home/user/filetoencode.txt\"\n"
	printf "\nOptions:\n"
	printf "%s\n" "-s            Encode string"
	printf "%s\n\n" "-f            Encode file"
	printf "%s\n" "for complex strings that need scape"
	printf "%s\n" "save the string you want to encode to a file"
	printf "%s\n" "and use -f flag to avoid errors"
	exit
}

if [[ -z "$1" ]] || [[ -z "$2" ]]
then
	usage
fi

if [[ "$1" == "-s" ]]
then
	printf "\n\e[1m[ Base64 UTF-8 format ]\e[0m Encoding string\n\n"
	printf "$2" | base64

	printf "\n\e[1m[ Base64 windows UNICODE format ]\e[0m Encoding string\n\n"
	printf "$2" | iconv -t utf-16le | base64 -w 0
fi

if [[ "$1" == "-f" ]]
then
	printf "\n\e[1m[ Base64 UTF-8 format ]\e[0m Encoding file $2\n\n"
	cat "$2" | base64

        printf "\n\e[1m[ Base64 windows UNICODE format ]\e[0m Encoding file $2\n\n"
	cat "$2" | iconv -t utf-16le | base64 -w 0
fi
