#!/bin/bash

function usage(){

	printf "Usage\nbash decimalencode -s \"Hello world\"\n"
        printf "bash decimalencode -f \"/home/user/filetoencode.txt\"\n"
        printf "\nOptions:\n"
        printf "%s\n" "-s            Encode string to decimal"
        printf "%s\n\n" "-f            Encode file to decimal"
	printf "%s\n" "for complex strings that need scape"
        printf "%s\n" "save the string you want to encode to a file"
        printf "%s\n" "and use -f flag to avoid errors"


}

if [[ -z "$1" ]] || [[ -z "$2" ]]
then
        usage
	exit
fi


if [[ "$1" == "-s" ]]
then
        printf "\nEncoding string $2 to decimal\n"
        decimal_encode_string=$(printf "$2" | od -td1 -An | tr -s " " | tr -t "\n" " " | tr -s " ")
	printf "$decimal_encode_string"
fi


if [[ "$1" == "-f" ]]
then
        printf "\nEncoding file $2 to decimal\n"
	decimal_encode_file=$(cat "$2" | od -td1 -An | tr -s " " | tr -t "\n" " " | tr -s " ")
        printf "$decimal_encode_file"
fi
