#!/bin/bash


function usage(){

	printf "bash base32decode -s \"Hello world\"\n"
	printf "bash base32decode -f \"/home/user/filetodecode.txt\"\n"
	printf "Options:\n"
	printf "%s\n" "-s            Decode string"
	printf "%s\n" "-f            Decode file"
	exit

}


if [[ -z "$1" ]] || [[ -z "$2" ]]
then
	usage
fi


if [[ "$1" == "-s" ]]
then
	printf "\nDecoding string $2 Base32 UTF-8 format\n"
	printf "$2" | base32 -d
fi


if [[ "$1" == "-f" ]]
then
	printf "\nDecoding file $2 Base32 UTF-8 format\n"
	cat "$2" | base32 -d
fi
