#!/bin/bash


function usage(){

	printf "bash base64decode -s \"Hello world\"\n"
	printf "bash base64decode -f \"/home/user/filetodecode.txt\"\n"
	printf "Valid for Base64 UTF-8 and Base64 WINDOWS UNICODE formats\n"
	printf "\nOptions:\n"
	printf "%s\n" "-s            Decode string"
	printf "%s\n\n" "-f            Decode file"
#	printf "%s\n" "for complex strings that need scape"
#        printf "%s\n" "save the string you want to decode to a file"
#        printf "%s\n" "and use -f flag to avoid errors"
	exit

}


if [[ -z "$1" ]] || [[ -z "$2" ]]
then
	usage
fi


if [[ "$1" == "-s" ]]
then
# #	printf "\n\e[1m[ UTF-8 & Windows Unicode ]\e[0m Decoding base64 string $2\n\n"
	printf "$2" | base64 -d
fi


if [[ "$1" == "-f" ]]
then
# #	printf "\n\e[1m[ UTF-8 & Windows Unicode ]\e[0m Decoding base64 file $2\n\n"
	cat "$2" | base64 -d
fi
